version: "{build}"

clone_depth: 1

clone_folder: c:\gopath\src\github.com\gen2brain\raylib-go

environment:
  GOPATH: c:\gopath
  MSYS_PATH: c:\msys64
  CGO_ENABLED: 1
  CGO_CFLAGS: -g -O2 -Ic:\msys64\mingw32\include
  GOARCH: 386
  CC: i686-w64-mingw32-gcc

install:
  - echo %GOPATH%
  - echo %MSYS_PATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%MSYS_PATH%\usr\bin;%MSYS_PATH%\mingw32\bin;%PATH%
  - go version
  - go env

build_script:
  - bash -lc "cd /c/gopath/src/github.com/gen2brain/raylib-go && go get -t ./... && make"
