on: [push, pull_request]
name: Build
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install package
      run: |
        sudo apt-get update -y; sudo apt-get -y install libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libgl1-mesa-dev libwayland-dev libxkbcommon-dev
      if: runner.os == 'Linux'
    - name: Build
      run: go build ./...
      working-directory: raylib
    - name: Verify dependencies
      run: go mod verify
      working-directory: raylib
    - name: Build
      run: go build -v ./...
      working-directory: raylib
    - name: Run go vet
      run: go vet ./...
      working-directory: raylib
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
      working-directory: raylib
    - name: Run staticcheck
      run: staticcheck ./...
      working-directory: raylib
    - name: Run tests
      run: go test -race -vet=off ./...
      working-directory: raylib

  test-drm:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install package
      run: |
        sudo apt-get update -y; sudo apt-get -y install libegl1-mesa-dev libdrm-dev libgbm-dev
    - name: Build
      run: go build -tags drm
      working-directory: raylib

  test-sdl2:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install package (Linux)
      run: |
        sudo apt-get update -y; sudo apt-get -y install libgl1-mesa-dev libsdl2-dev
      if: runner.os == 'Linux'
    - name: Install package (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install sdl2
    - name: Setup MSYS2 and SDL2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-SDL2
    - name: Build (SDL2, non-Windows)
      if: runner.os != 'Windows'
      run: go build -tags sdl2
      working-directory: raylib
    - name: Build (SDL2, Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: go build -tags sdl2
      working-directory: raylib
      env:
        CGO_ENABLED: 1
        CC: x86_64-w64-mingw32-gcc

  test-sdl3:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install SDL3 (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get -y install libgl1-mesa-dev
        git clone https://github.com/libsdl-org/SDL.git
        cd SDL
        mkdir build
        cd build
        cmake .. -DSDL_SHARED=ON -DSDL_STATIC=OFF # or configure as needed
        make -j$(nproc)
        sudo make install
    - name: Install SDL3 (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install sdl3
    - name: Setup MSYS2 and SDL3 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-SDL3
    - name: Build (SDL3, non-Windows)
      if: runner.os != 'Windows'
      run: go build -tags sdl3
      working-directory: raylib
    - name: Build (SDL3, Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: go build -tags sdl3
      working-directory: raylib
      env:
        CGO_ENABLED: 1
        CC: x86_64-w64-mingw32-gcc

  test-rgfw:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install package
      run: |
        sudo apt-get update -y; sudo apt-get -y install libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libgl1-mesa-dev libxkbcommon-dev
      if: runner.os == 'Linux'
    - name: Build
      run: go build -tags rgfw
      working-directory: raylib

  test-purego:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: go build
      working-directory: raylib
      env:
        GOOS: windows

  test-examples:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install package
      run: |
        sudo apt-get update -y; sudo apt-get -y install libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libgl1-mesa-dev libwayland-dev libxkbcommon-dev
    - name: Build
      run: go build ./...
      working-directory: examples
